# -*- coding: utf-8 -*-
"""BNN-COX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2sQ6dsXc0QRQNdFeliuBxGxjzej97Eq

# **Weld Data**
"""

import pandas as pd

df1= pd.read_excel("Weld Fracture_IR_Since_01-01-2015.xlsx")
df1.columns
filtered_df1= df1[df1["RLYCODE"]=="NCR"]
filtered_df1["DATE_OF_WELDING"]=pd.to_datetime(filtered_df1["DATE_OF_WELDING"], dayfirst=True, errors="coerce")
filtered_df1["FRACTURE_DATE"]=pd.to_datetime(filtered_df1["FRACTURE_DATE"], dayfirst=True, errors="coerce")
filtered_df1= filtered_df1.drop(columns="TIME_OF_DETECTION")
filtered_df1=filtered_df1.drop(columns="RLYCODE")
filtered_df1["DIVCODE"].unique()
len(filtered_df1.columns)

filtered_df1.columns

mapping = {
    'UP': 'Main_Run',
    'DN': 'Main_Run',
    'SL': 'Main_Run',
    'S':  'Main_Run',
    'IIIrd Line': 'Multi_Run'
}

filtered_df1['LINE'] = filtered_df1['LINE'].map(mapping).fillna('Non_Main')

filtered_df1['LINE'].value_counts()

mapping = {
    'GW': 'GW',
    'DFWO': 'DFW',
    'DFWO Joggled Plate': 'DFW',
    'DFWR': 'DFW',
    'DFWR Joggled Plate': 'DFW',
    'DFW Joggled Plate': 'DFW',
    'OBS(W) Joggled Plate': 'OBS',
    'OBS(W)': 'OBS'
}

filtered_df1['USFD_CLASSIFICATION'] = filtered_df1['USFD_CLASSIFICATION'].map(mapping)

filtered_df1["USFD_CLASSIFICATION"].unique()

df_AGRA= pd.read_excel("Weld_Master_NCR_AGRA_AsOn_30_09_2025.xlsx")
df_PRYJ= pd.read_excel("Weld_Master_NCR_PRYJ_AsOn_30_09_2025.xlsx")
df_JHS= pd.read_excel("Weld_Master_NCR_JHS_AsOn_30_09_2025.xlsx")

df2= pd.concat([df_AGRA,df_PRYJ,df_JHS], ignore_index= True)

filtered_df2=df2.drop(columns=["RLYCODE"])

filtered_df2["USFD_CLASSIFICATION"].unique()

filtered_df2=filtered_df2.rename(columns={"LRRR": "LR_RR"})

mapping = {
    'GW': 'GW',
    'DFWO(JP)': 'DFW',
    'DFWR(JP)': 'DFW',
    'DFWN': 'DFW',
    'DFW(JP)': 'DFW',
    'OBS(W)(JP)': 'OBS'
}

filtered_df2['USFD_CLASSIFICATION'] = filtered_df2['USFD_CLASSIFICATION'].map(mapping)

mapping = {
    'SL':           'Main_Run',
    'S':            'Main_Run',
    'UP':           'Main_Run',
    'DN':           'Main_Run',
    'IIIrd Line':   'Multi_Run',
    'IVth Line':    'Multi_Run',
    'A Line':       'Multi_Run',
    'MID':          'Non_Main',
    'N':            'Non_Main',
    'OML':          'Non_Main',
    'Chord Line':   'Non_Main',
    'Yard':         'Non_Main'
}

filtered_df2['LINE'] = filtered_df2['LINE'].map(mapping).fillna('Non_Main')

filtered_df2["USFD_CLASSIFICATION"].unique()

filtered_df2.columns

filtered_df1.columns

filtered_df1["AXLE_LOAD"]=pd.to_numeric(filtered_df1["AXLE_LOAD"], errors="coerce")

final_df= pd.concat([filtered_df1,filtered_df2], ignore_index= True)

final_df

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
import sklearn
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold

# ---------------------
# 1) Column sets
# ---------------------
ohe_cols = ["DIVCODE", "LINE", "LR_RR", "TYPE_OF_WELD", "USFD_CLASSIFICATION", "RAIL_SECTION"]
num_cols = ["AXLE_LOAD", "GMT_CARRIED", "ANNUAL_GMT", "SPEED", "KM", "MET"]
start_col = "DATE_OF_WELDING"
end_col   = "FRACTURE_DATE"
section_col = "SECTION"           # entity encoding column

# ---------------------
# 2) Small transformers
# ---------------------
class AddEventFlag(BaseEstimator, TransformerMixin):
    """event = 1 if end date present, else 0."""
    def __init__(self, fracture_col=end_col):
        self.fracture_col = fracture_col
    def fit(self, X, y=None): return self
    def transform(self, X):
        X_ = X.copy()
        X_["event"] = np.where(pd.to_datetime(X_[self.fracture_col], errors="coerce").notna(), 1, 0)
        return X_

class DurationCalculator(BaseEstimator, TransformerMixin):
    """DURATION = (end - start).days; drops the two date cols."""
    def __init__(self, start_col=start_col, end_col=end_col, dayfirst=True):
        self.start_col, self.end_col, self.dayfirst = start_col, end_col, dayfirst
    def fit(self, X, y=None): return self
    def transform(self, X):
        X_ = X.copy()
        start = pd.to_datetime(X_[self.start_col], dayfirst=self.dayfirst, errors="coerce")
        end   = pd.to_datetime(X_[self.end_col],   dayfirst=self.dayfirst, errors="coerce")
        X_["DURATION"] = (end - start).dt.days
        X_.drop(columns=[self.start_col, self.end_col], inplace=True)
        return X_

class KFoldTargetEncoder(BaseEstimator, TransformerMixin):
    """OOF mean encoding for a single categorical column (SECTION)."""
    def __init__(self, col=section_col, n_splits=5, noise=0.0, random_state=42):
        self.col, self.n_splits, self.noise, self.random_state = col, n_splits, noise, random_state
    def fit(self, X, y):
        s = X[self.col].astype("category")
        self.global_mean_ = float(np.nanmean(y))
        self.cat_mean_ = pd.DataFrame({self.col: s, "_y": y}).groupby(self.col)["_y"].mean()
        return self
    def transform(self, X):
        s = X[self.col].astype("category")
        enc = s.map(self.cat_mean_).astype("float64").fillna(self.global_mean_)
        if self.noise > 0:
            enc = enc + np.random.RandomState(self.random_state).normal(0, self.noise, size=len(enc))
        return enc.to_numpy().reshape(-1, 1)
    def fit_transform(self, X, y):
        s = X[self.col].astype("category")
        kf = KFold(n_splits=self.n_splits, shuffle=True, random_state=self.random_state)
        oof = pd.Series(index=X.index, dtype="float64")
        y_arr = np.asarray(y)
        for tr, va in kf.split(X):
            means = pd.DataFrame({self.col: s.iloc[tr], "_y": y_arr[tr]}).groupby(self.col)["_y"].mean()
            oof.iloc[va] = s.iloc[va].map(means).astype("float64").fillna(float(np.nanmean(y_arr[tr])))
        self.fit(X, y)  # set full-data stats for inference
        if self.noise > 0:
            oof = oof + np.random.RandomState(self.random_state).normal(0, self.noise, size=len(oof))
        return oof.to_numpy().reshape(-1, 1)

class AddSectionEncoded(BaseEstimator, TransformerMixin):
    """Adds SECTION_ENC numeric column using target encoder."""
    def __init__(self, encoder: KFoldTargetEncoder):
        self.encoder = encoder
    def fit(self, X, y):
        self.encoder.fit(X, y)  # uses target y for mean encoding
        return self
    def transform(self, X):
        X_ = X.copy()
        X_["SECTION_ENC"] = self.encoder.transform(X)
        return X_

# ---------------------
# 3) ColumnTransformer for features
# ---------------------
if sklearn.__version__ >= "1.2":
    ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
else:
    ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse=False)
num_tf  = StandardScaler()

feature_ct = ColumnTransformer(
    transformers=[
        ("ohe",   ohe_tf,  ohe_cols),
        ("num",   num_tf,  num_cols),
        ("sec",   "passthrough", ["SECTION_ENC"])
    ],
    remainder="drop"
)

# ---------------------
# 4) Master preprocessing pipeline (no estimator)
# ---------------------
preprocess_pipeline = Pipeline(steps=[
    ("add_event",       AddEventFlag(fracture_col=end_col)),
    ("add_duration",    DurationCalculator(start_col=start_col, end_col=end_col, dayfirst=True)),
    ("add_section_enc", AddSectionEncoded(KFoldTargetEncoder(col=section_col))),
    ("features",        feature_ct),        # outputs X only (features + DURATION); event is not included here
])

# ---------------------
# 5) Usage
# ---------------------
# final_df: your concatenated dataframe (failures + non-failures).
# y_event and y_time should be taken from an intermediate copy to avoid mixing into features.

def prepare_survival_tensors(final_df: pd.DataFrame):
    """Returns X (features), y_time (duration), y_event, and the fitted preprocessing pipeline."""
    # compute event/duration in a side copy (mirrors pipeline steps)
    tmp = final_df.copy()
    tmp["event"] = np.where(pd.to_datetime(tmp[end_col], errors="coerce").notna(), 1, 0)
    start = pd.to_datetime(tmp[start_col], dayfirst=True, errors="coerce")
    end   = pd.to_datetime(tmp[end_col],   dayfirst=True, errors="coerce")
    tmp["DURATION"] = (end - start).dt.days

    y_event = tmp["event"].to_numpy().astype(int)
    y_time  = tmp["DURATION"].to_numpy().astype(float)

    # Fit-transform features (target encoder needs a target; use y_event)
    X = preprocess_pipeline.fit_transform(final_df, y_event)

    return X, y_time, y_event, preprocess_pipeline

# Example:
# X, y_time, y_event, pp = prepare_survival_tensors(final_df)
# -> feed (X, y_time, y_event) to your Cox-BNN training code.

final_df.columns

import numpy as np
import pandas as pd
import sklearn
from scipy.optimize import minimize
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer


# =====================================================
# 1. COLUMN DEFINITIONS
# =====================================================

ohe_cols = [
    "DIVCODE",
    "LINE",
    "LR_RR",
    "TYPE_OF_WELD",
    "USFD_CLASSIFICATION",
    "RAIL_SECTION"
]

num_cols = [
    "AXLE_LOAD",
    "GMT_CARRIED",
    "ANNUAL_GMT",
    "SPEED",
    "KM",
    "MET"
]

section_col = "SECTION"
start_col = "DATE_OF_WELDING"
event_col = "FRACTURE_DATE"


# =====================================================
# 2. PREPROCESS FUNCTION
# =====================================================

def prepare_survival_data(df):

    df = df.copy()

    # ---- parse dates
    start = pd.to_datetime(df[start_col], errors="coerce", dayfirst=True)
    fracture = pd.to_datetime(df[event_col], errors="coerce", dayfirst=True)

    # ---- event indicator
    df["event"] = fracture.notna().astype(int)

# ---- duration for fractured rows
    duration_event = (fracture - start).dt.days

# ---- administrative censoring time (dataset end)
    admin_censor_date = fracture.max()

# ---- duration for censored rows
    duration_censor = (admin_censor_date - start).dt.days

# ---- assign duration
    df["DURATION"] = duration_event
    df.loc[df["event"] == 0, "DURATION"] = duration_censor[df["event"] == 0]

    # ---- remove invalid rows
    mask = (
        start.notna()
        & df["DURATION"].notna()
        & (df["DURATION"] >= 0)
    )

    df = df.loc[mask].copy()

    # ---- SECTION frequency encoding
    freq_map = df[section_col].value_counts(normalize=True).to_dict()

    df["SECTION_FREQ"] = (
        df[section_col]
        .map(freq_map)
        .fillna(0)
    )

    # ---- feature matrix
    feature_cols = ohe_cols + num_cols + ["SECTION_FREQ"]

    X_input = df[feature_cols].copy()

    # ---- encoders
    if sklearn.__version__ >= "1.2":
        ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    else:
        ohe_tf = OneHotEncoder(handle_unknown="ignore", sparse=False)

    num_tf = StandardScaler()

    feature_ct = ColumnTransformer(
        transformers=[
            ("ohe", ohe_tf, ohe_cols),
            ("num", num_tf, num_cols),
            ("sec", "passthrough", ["SECTION_FREQ"])
        ],
        remainder="drop"
    )

    X = feature_ct.fit_transform(X_input)

    feature_names = feature_ct.get_feature_names_out()

    X_df = pd.DataFrame(X, columns=feature_names)

    # ---- targets
    T = df["DURATION"].to_numpy(dtype=float)
    E = df["event"].to_numpy(dtype=int)

    # ---- final checks
    mask = (
        np.isfinite(T)
        & np.isfinite(E)
        & np.all(np.isfinite(X), axis=1)
    )

    X_df = X_df.loc[mask]
    X = X[mask]
    T = T[mask]
    E = E[mask]

    # ---- breaks
    breaks = np.quantile(T, np.linspace(0, 1, 11))
    breaks[0] = 0.0
    breaks = np.unique(breaks)

    if breaks[-1] < np.max(T):
        breaks = np.append(breaks, np.max(T))

    return X_df, X, T, E, breaks

X_df, X, T, E, breaks = prepare_survival_data(final_df)

!pip install lifelines

import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
import tf_keras as keras
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

tf.keras.backend.set_floatx("float32")
tfd = tfp.distributions


# ============================================================
# 0) START FROM CURRENT PREPROCESSED OBJECTS
#    Assumes these already exist:
#    X_df, X, T, E = prepare_survival_data(final_df)
# ============================================================

# Safety: rebuild aligned dataframe-like container from current outputs
dfv = pd.DataFrame(X, columns=X_df.columns)
dfv["time"] = T
dfv["event"] = E

# Filter exactly like rail pipeline style
dfv = dfv[dfv["time"].notna()].copy()
dfv = dfv[dfv["time"] > 0].copy()
dfv = dfv[dfv["event"].notna()].copy()

# Rebuild X, T, E from filtered dfv
T = dfv["time"].to_numpy(np.float32)
E = dfv["event"].astype(int).to_numpy(np.int32)

X_df_filtered = dfv.drop(columns=["time", "event"], errors="ignore").copy()
X = X_df_filtered.to_numpy(np.float32)

print("Final aligned shapes:", X.shape, T.shape, E.shape)
print("NaNs in T:", np.isnan(T).sum())
print("Min T:", float(np.nanmin(T)))
print("Event distribution:", np.unique(E, return_counts=True))

assert np.isnan(T).sum() == 0
assert float(np.min(T)) > 0
assert X.shape[0] == len(T) == len(E)


# ============================================================
# 1) TRAIN/TEST SPLIT
# ============================================================

X_train, X_test, y_time_tr, y_time_te, y_event_tr, y_event_te = train_test_split(
    X,
    T,
    E,
    test_size=0.2,
    random_state=42,
    stratify=E
)

print("Train X shape:", X_train.shape, "| Test X shape:", X_test.shape)
print("Train event distribution:", np.unique(y_event_tr, return_counts=True))
print("Test event distribution:", np.unique(y_event_te, return_counts=True))

assert set(np.unique(y_event_te)) == {0, 1}, "Test set missing a class!"


# ============================================================
# 2) SCALE FEATURES FOR BNN STABILITY
#    Same spirit as rail Cox-BNN pipeline
# ============================================================

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train).astype(np.float32)
X_test_s = scaler.transform(X_test).astype(np.float32)

print("NaN count in X_train_s:", np.isnan(X_train_s).sum())
print("NaN count in y_time_tr:", np.isnan(y_time_tr).sum())
print("NaN count in y_event_tr:", np.isnan(y_event_tr).sum())
print("Rows in X_train_s with at least one NaN:", np.isnan(X_train_s).any(axis=1).sum())

assert np.isnan(X_train_s).sum() == 0
assert np.isnan(X_test_s).sum() == 0


# ============================================================
# 3) TIMER CALLBACK
# ============================================================

class EpochTimer(keras.callbacks.Callback):
    def on_train_begin(self, logs=None):
        self.global_start = time.time()
        print("\nTraining started...\n")

    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_start = time.time()

    def on_epoch_end(self, epoch, logs=None):
        epoch_time = time.time() - self.epoch_start
        total_time = time.time() - self.global_start
        loss = logs.get("loss", float("nan"))
        val_loss = logs.get("val_loss", float("nan"))

        print(
            f"Epoch {epoch+1:03d} | "
            f"loss={loss:.4f} | "
            f"val_loss={val_loss:.4f} | "
            f"epoch_time={epoch_time:.2f}s | "
            f"total_time={total_time/60:.2f} min"
        )

    def on_train_end(self, logs=None):
        total_time = time.time() - self.global_start
        print(f"\nTraining finished in {total_time/60:.2f} minutes.\n")


# ============================================================
# 4) BAYESIAN BNN PIECES
# ============================================================

def prior_fn(dtype, shape, name, trainable, add_variable_fn):
    del name, trainable, add_variable_fn
    return tfd.Independent(
        tfd.Normal(
            loc=tf.zeros(shape, dtype=dtype),
            scale=tf.ones(shape, dtype=dtype)
        ),
        reinterpreted_batch_ndims=len(shape)
    )

posterior_fn = tfp.layers.default_mean_field_normal_fn(
    is_singular=False,
    loc_initializer=keras.initializers.Zeros(),
    untransformed_scale_initializer=keras.initializers.Constant(-2.2)
)

def kl_sum(q, p, _):
    return 1e-5 * tf.reduce_sum(tfp.distributions.kl_divergence(q, p))


# ============================================================
# 5) BUILD BNN
# ============================================================

def build_bnn(input_dim: int):
    inputs = keras.Input(shape=(int(input_dim),), dtype="float32", name="x")

    x = tfp.layers.DenseReparameterization(
        64,
        activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum,
        bias_divergence_fn=kl_sum
    )(inputs)

    x = tfp.layers.DenseReparameterization(
        32,
        activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum,
        bias_divergence_fn=kl_sum
    )(x)

    outputs = tfp.layers.DenseReparameterization(
        1,
        activation=None,
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum,
        bias_divergence_fn=kl_sum
    )(x)

    return keras.Model(inputs, outputs, name="BNN_gX")


# ============================================================
# 6) COX PARTIAL LIKELIHOOD LOSS
#    Full-risk-set version, same style as rail pipeline
# ============================================================

@tf.function
def neg_log_partial_lik(y_true, y_pred):
    event = tf.cast(y_true[:, 0], tf.float32)
    time_ = tf.cast(y_true[:, 1], tf.float32)
    risk = tf.cast(tf.squeeze(y_pred, axis=-1), tf.float32)

    # sort by time descending
    order = tf.argsort(time_, direction="DESCENDING")
    time_ = tf.gather(time_, order)
    event = tf.gather(event, order)
    risk = tf.gather(risk, order)

    # prefix cumulative logsumexp
    lse_prefix = tf.math.cumulative_logsumexp(risk)

    # Breslow tie handling
    is_new = tf.concat([[True], tf.not_equal(time_[1:], time_[:-1])], axis=0)
    gid = tf.cumsum(tf.cast(is_new, tf.int32)) - 1

    is_end = tf.concat([tf.not_equal(time_[:-1], time_[1:]), [True]], axis=0)
    end_lse = tf.boolean_mask(lse_prefix, is_end)
    denom = tf.gather(end_lse, gid)

    loglik = tf.reduce_sum(event * (risk - denom))
    return -loglik / (tf.reduce_sum(event) + 1e-8)


# ============================================================
# 7) TRAIN BNN AND GET g(x)
#    Full batch because Cox loss depends on full risk sets
# ============================================================

def train_bnn_and_get_g(X_tr, time_tr, event_tr, X_te, lr=1e-3, epochs=100):
    model = build_bnn(X_tr.shape[1])
    model.compile(
        optimizer=keras.optimizers.RMSprop(lr),
        loss=neg_log_partial_lik
    )

    y_tr = np.column_stack([event_tr, time_tr]).astype(np.float32)

    es = keras.callbacks.EarlyStopping(
        patience=10,
        restore_best_weights=True
    )

    timer = EpochTimer()

    model.fit(
        X_tr.astype(np.float32),
        y_tr,
        batch_size=X_tr.shape[0],   # full batch is important here
        epochs=epochs,
        verbose=0,
        validation_split=0.2,
        shuffle=False,
        callbacks=[es, timer]
    )

    g_tr = model.predict(X_tr.astype(np.float32), verbose=0).reshape(-1)
    g_te = model.predict(X_te.astype(np.float32), verbose=0).reshape(-1)

    return g_tr, g_te


# ============================================================
# 8) TRAIN BNN NONLINEAR TERM
# ============================================================

g_tr, g_te = train_bnn_and_get_g(
    X_train_s,
    y_time_tr,
    y_event_tr,
    X_test_s,
    lr=1e-3,
    epochs=100
)


# ============================================================
# 9) HYBRID LINEAR COX PART
#    Use current weld feature names from X_df_filtered.columns
# ============================================================

feature_names = list(X_df_filtered.columns)

# ===============================
# Select treatment variables (SET 1)
# ===============================

#colnames = list(X_df.columns)   # must match the matrix used to build X
colnames = list(X_df_filtered.columns)

def find_col(name):
    matches = [i for i,c in enumerate(colnames) if name in c]
    if len(matches) == 0:
        raise ValueError(f"{name} not found")
    return matches[0]


idx_line  = find_col("ohe__LINE")
idx_lr    = find_col("ohe__LR_RR")
idx_weld  = find_col("ohe__TYPE_OF_WELD")
idx_rail  = find_col("ohe__RAIL_SECTION")
idx_usfd  = find_col("ohe__USFD_CLASSIFICATION")

idx_speed  = find_col("num__SPEED")
idx_annual = find_col("num__ANNUAL_GMT")
idx_gmt    = find_col("num__GMT_CARRIED")
idx_axle   = find_col("num__AXLE_LOAD")

treat_idx = [
    idx_line
    , idx_lr
    , idx_weld
    , idx_rail
    , idx_usfd
    , idx_speed
    , idx_annual
    , idx_gmt
    , idx_axle
]

X_lin_tr = X_train[:, treat_idx]
X_lin_te = X_test[:, treat_idx]

col_treat = [colnames[i] for i in treat_idx]

train_df = pd.DataFrame(X_lin_tr, columns=col_treat)
train_df["time"] = y_time_tr
train_df["event"] = y_event_tr
train_df["g_bnn"] = g_tr

test_df = pd.DataFrame(X_lin_te, columns=col_treat)
test_df["time"] = y_time_te
test_df["event"] = y_event_te
test_df["g_bnn"] = g_te

formula = " + ".join(col_treat) + " + g_bnn"


# ============================================================
# 10) FIT HYBRID COX MODEL
# ============================================================

cph = CoxPHFitter()
cph.fit(
    train_df,
    duration_col="time",
    event_col="event",
    formula=formula
)

print("\nCox coefficients:")
print(cph.params_)


# ============================================================
# 11) C-INDEX
# ============================================================

risk_tr = cph.predict_partial_hazard(train_df).values.ravel()
risk_te = cph.predict_partial_hazard(test_df).values.ravel()

c_tr = concordance_index(
    train_df["time"].values,
    -risk_tr,
    train_df["event"].values
)

c_te = concordance_index(
    test_df["time"].values,
    -risk_te,
    test_df["event"].values
)

print(f"\nC-index train = {c_tr:.3f}")
print(f"C-index test  = {c_te:.3f}")

|print("Feature count:", len(X_df_filtered.columns))
print("Matrix width:", X_train.shape[1])

import numpy as np

# survival matrix already computed for IBS
# S_pred shape = (n_test, n_times)

times = times_ibs


def median_time_from_curve(times, s_row):

    idx = np.where(s_row <= 0.5)[0]

    if len(idx) == 0:
        return times[-1]

    return times[idx[0]]


# predicted median survival
t50_pred = np.array(
    [median_time_from_curve(times, s_row) for s_row in S_pred],
    dtype=float
)

# evaluate only on events
mask_event = (y_event_te == 1)

rmse = np.sqrt(
    np.mean(
        (t50_pred[mask_event] - y_time_te[mask_event]) ** 2
    )
)

print("RMSE (median survival time, events only):", float(rmse))
print("Num events used:", int(mask_event.sum()))

!pip install scikit-survival

import numpy as np
from sksurv.metrics import integrated_brier_score
from sksurv.util import Surv

# structured arrays
y_train_struct = Surv.from_arrays(
    y_event_tr.astype(bool),
    y_time_tr.astype(float)
)

y_test_struct = Surv.from_arrays(
    y_event_te.astype(bool),
    y_time_te.astype(float)
)

# time grid (must lie within follow-up)
t_min = float(np.min(y_time_te))
t_max = float(np.max(y_time_te))
eps = np.nextafter(t_max, -np.inf)

times_ibs = np.linspace(t_min, eps, 200)

# predicted survival curves
surv_df = cph.predict_survival_function(test_df, times=times_ibs)

# convert to matrix
S_pred = surv_df.to_numpy().T   # (n_test, n_times)

# IBS
ibs = integrated_brier_score(
    y_train_struct,
    y_test_struct,
    S_pred,
    times_ibs
)

print("IBS:", float(ibs))

print("Min duration:", np.min(y_time_te))
print("Median duration:", np.median(y_time_te))
print("Max duration:", np.max(y_time_te))

"""# COX+**BNN**"""

!pip install lifelines

import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
import tf_keras as keras
import time

tfd = tfp.distributions


# ================= Timer =================
class EpochTimer(keras.callbacks.Callback):

    def on_train_begin(self, logs=None):
        self.t0 = time.time()

    def on_epoch_begin(self, epoch, logs=None):
        self.e0 = time.time()
        print(f"\nEpoch {epoch+1} started...")

    def on_epoch_end(self, epoch, logs=None):
        dt = time.time() - self.e0
        total = (time.time() - self.t0) / 60
        print(
            f"Epoch {epoch+1} ended — {dt:.2f}s | "
            f"loss {logs['loss']:.4f} | val {logs['val_loss']:.4f} | "
            f"total {total:.1f} min"
        )


# ================= Bayesian Pieces =================

def prior_fn(dtype, shape, name, trainable, add_variable_fn):
    del name, trainable, add_variable_fn
    return tfd.Independent(
        tfd.Normal(
            loc=tf.zeros(shape, dtype=dtype),
            scale=tf.ones(shape, dtype=dtype)
        ),
        reinterpreted_batch_ndims=len(shape)
    )


posterior_fn = tfp.layers.default_mean_field_normal_fn(
    loc_initializer=keras.initializers.Zeros(),
    untransformed_scale_initializer=keras.initializers.Constant(-2.2)
)


def kl_sum(q, p, _):
    return 1e-5 * tf.reduce_sum(tfp.distributions.kl_divergence(q, p))


# ================= Smaller BNN =================

def build_bnn(input_dim):

    inputs = keras.Input(shape=(input_dim,), dtype="float32")

    x = tfp.layers.DenseReparameterization(
        32, activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum
    )(inputs)

    x = tfp.layers.DenseReparameterization(
        16, activation="relu",
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum
    )(x)

    outputs = tfp.layers.DenseReparameterization(
        1,
        kernel_prior_fn=prior_fn,
        kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum
    )(x)

    return keras.Model(inputs, outputs)


# ================= Faster Cox Loss =================

@tf.function
def neg_log_partial_lik(y_true, y_pred):

    event = y_true[:, 0]
    risk = tf.squeeze(y_pred, axis=-1)

    # cumulative log-sum-exp
    log_cumsum = tf.math.log(
        tf.cumsum(tf.exp(risk), reverse=True) + 1e-12
    )

    loglik = tf.reduce_sum(event * (risk - log_cumsum))

    return -loglik / (tf.reduce_sum(event) + 1e-8)


# ================= Training =================

def train_bnn_and_get_g(X_tr, time_tr, event_tr, X_te):

    # ---- Sort once for Cox loss ----
    order = np.argsort(-time_tr)

    X_tr = X_tr[order]
    time_tr = time_tr[order]
    event_tr = event_tr[order]

    y_tr = np.column_stack([event_tr, time_tr]).astype(np.float32)

    # ---- Train/validation split ----
    n = X_tr.shape[0]
    split = int(n * 0.8)

    X_train = X_tr[:split]
    y_train = y_tr[:split]

    X_val = X_tr[split:]
    y_val = y_tr[split:]

    # ---- tf.data datasets ----
    train_ds = (
        tf.data.Dataset
        .from_tensor_slices((X_train.astype(np.float32), y_train))
        .shuffle(10000)
        .batch(4096)
        .prefetch(tf.data.AUTOTUNE)
    )

    val_ds = (
        tf.data.Dataset
        .from_tensor_slices((X_val.astype(np.float32), y_val))
        .batch(4096)
        .prefetch(tf.data.AUTOTUNE)
    )

    # ---- Model ----
    model = build_bnn(X_tr.shape[1])

    model.compile(
        optimizer=keras.optimizers.Adam(1e-3),
        loss=neg_log_partial_lik
    )

    es = keras.callbacks.EarlyStopping(
        patience=5,
        restore_best_weights=True
    )

    timer = EpochTimer()

    # ---- Train ----
    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=30,
        callbacks=[es, timer],
        verbose=0
    )

    # ---- Predictions ----
    g_tr = model.predict(X_tr.astype(np.float32), batch_size=8192).reshape(-1)
    g_te = model.predict(X_te.astype(np.float32), batch_size=8192).reshape(-1)

    return g_tr, g_te

!pip install tensorflow-probability

import tensorflow_probability as tfp
tfd = tfp.distributions

final_df.columns

feature_names = pp.named_steps["features"].get_feature_names_out()
feature_names

# === BNN training ===
g_tr_sorted, g_te = train_bnn_and_get_g(
    X_train,
    y_time_tr,
    y_event_tr,
    X_test
)

# === restore original order (because BNN sorted by time) ===
order = np.argsort(-y_time_tr)
inv_order = np.argsort(order)

g_tr = g_tr_sorted[inv_order]


# ===============================
# Select linear Cox variables
# ===============================

import pandas as pd

feature_names = pp.named_steps["features"].get_feature_names_out()


def find_col(col_name):
    matches = [i for i, name in enumerate(feature_names) if col_name in name]
    if len(matches) == 0:
        raise ValueError(f"{col_name} not found in feature names")
    if len(matches) > 1:
        print(f"Warning: multiple matches for {col_name}, using first: {feature_names[matches[0]]}")
    return matches[0]


# === column indices ===
# indices
i_axle   = find_col("AXLE_LOAD")
i_gmt    = find_col("GMT_CARRIED")
i_annual = find_col("ANNUAL_GMT")

i_rail_52 = find_col("RAIL_SECTION_52KG")
i_rail_60 = find_col("RAIL_SECTION_60KG")
# drop OTHER to avoid singular matrix

X_lin_tr = X_train[:, [i_axle, i_gmt, i_annual, i_rail_52, i_rail_60]]
X_lin_te = X_test[:,  [i_axle, i_gmt, i_annual, i_rail_52, i_rail_60]]


train_df = pd.DataFrame({
    "time": y_time_tr,
    "event": y_event_tr,
    "AXLE_LOAD": X_lin_tr[:,0],
    "GMT_CARRIED": X_lin_tr[:,1],
    "ANNUAL_GMT": X_lin_tr[:,2],
    "RAIL_52KG": X_lin_tr[:,3],
    "RAIL_60KG": X_lin_tr[:,4],
    "g_bnn": g_tr
})

test_df = pd.DataFrame({
    "time": y_time_te,
    "event": y_event_te,
    "AXLE_LOAD": X_lin_te[:,0],
    "GMT_CARRIED": X_lin_te[:,1],
    "ANNUAL_GMT": X_lin_te[:,2],
    "RAIL_52KG": X_lin_te[:,3],
    "RAIL_60KG": X_lin_te[:,4],
    "g_bnn": g_te
})

# === Cox formula ===
formula = "AXLE_LOAD + GMT_CARRIED + ANNUAL_GMT + RAIL_52KG + RAIL_60KG + g_bnn"





# ===============================
# Fit Cox Model
# ===============================

from lifelines import CoxPHFitter
from lifelines.utils import concordance_index

cph = CoxPHFitter()

cph.fit(
    train_df,
    duration_col="time",
    event_col="event",
    formula=formula
)


# ===============================
# Print coefficients
# ===============================

print("\nCox coefficients")
print(cph.params_)


# ===============================
# Compute C-index
# ===============================

risk_tr = cph.predict_partial_hazard(train_df).values.ravel()
risk_te = cph.predict_partial_hazard(test_df).values.ravel()

c_tr = concordance_index(
    train_df["time"].values,
    -risk_tr,
    train_df["event"].values
)

c_te = concordance_index(
    test_df["time"].values,
    -risk_te,
    test_df["event"].values
)

print(f"\nC-index train = {c_tr:.3f}")
print(f"C-index test  = {c_te:.3f}")

train_df["event"].value_counts()

np.isfinite(train_df["g_bnn"]).all()

"""# ***RAIL DATA***"""

import pandas as pd

df_processed=pd.read_pickle("processed_df.pkl")

len(df_processed.columns)

import numpy as np

df_processed.columns

drop_cols = [
    "num__DURATION",
    "num__Event",
    "date__FRACTURE_TIMESTAMP",
    "date__LAYING_DATE",
    "date__USFDTIMESTAMP"
]

valid = (
    df_processed["num__DURATION"].notna() &
    (df_processed["num__DURATION"] > 0)
)

df = df_processed.loc[valid].copy()


X_df = df.drop(columns=drop_cols, errors="ignore")

X = X_df.to_numpy(np.float32)
T = df_processed["num__DURATION"].to_numpy(np.float32)
E = df_processed["num__Event"].to_numpy(np.int32)

dfv = df_processed.copy()

dfv = dfv[dfv["num__DURATION"].notna()]
dfv = dfv[dfv["num__DURATION"] > 0]
dfv = dfv[dfv["num__Event"].notna()]

# NOW build everything from dfv

T = dfv["num__DURATION"].to_numpy(np.float32)
E = dfv["num__Event"].astype(int).to_numpy(np.int32)

drop_cols = [
    "num__DURATION",
    "num__Event",
    "date__FRACTURE_TIMESTAMP",
    "date__LAYING_DATE",
    "date__USFDTIMESTAMP",
]

X_df = dfv.drop(columns=drop_cols, errors="ignore")
X = X_df.to_numpy(np.float32)

print(len(X), len(T), len(E))

from sklearn.model_selection import train_test_split

X_train, X_test, y_time_tr, y_time_te, y_event_tr, y_event_te = train_test_split(
    X,
    T,
    E,
    test_size=0.2,
    random_state=42,
    stratify=E
)

valid_tr = (~np.isnan(y_time_tr)) & (y_time_tr > 0)
valid_te = (~np.isnan(y_time_te)) & (y_time_te > 0)

X_train = X_train[valid_tr]
y_time_tr = y_time_tr[valid_tr]
y_event_tr = y_event_tr[valid_tr]

X_test = X_test[valid_te]
y_time_te = y_time_te[valid_te]
y_event_te = y_event_te[valid_te]

print(np.isnan(y_time_tr).sum(), y_time_tr.min())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

import tensorflow as tf

print("GPU Available:", tf.config.list_physical_devices('GPU'))

!pip install lifelines

df.columns

df_processed.columns

import numpy as np, pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
import tf_keras as keras
from lifelines import CoxPHFitter
from lifelines.utils import concordance_index
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import time
tf.keras.backend.set_floatx('float32')

# =========================
# 0) MUST: define tfd
# =========================
tfd = tfp.distributions

# =========================
# 1) Timer callback
# =========================
class EpochTimer(keras.callbacks.Callback):
    def on_train_begin(self, logs=None):
        self.global_start = time.time()
        print("\nTraining started...\n")

    def on_epoch_begin(self, epoch, logs=None):
        self.epoch_start = time.time()

    def on_epoch_end(self, epoch, logs=None):
        epoch_time = time.time() - self.epoch_start
        total_time = time.time() - self.global_start
        loss = logs.get("loss", float("nan"))
        val_loss = logs.get("val_loss", float("nan"))

        print(
            f"Epoch {epoch+1:03d} | "
            f"loss={loss:.4f} | "
            f"val_loss={val_loss:.4f} | "
            f"epoch_time={epoch_time:.2f}s | "
            f"total_time={total_time/60:.2f} min"
        )

    def on_train_end(self, logs=None):
        total_time = time.time() - self.global_start
        print(f"\nTraining finished in {total_time/60:.2f} minutes.\n")

# =========================
# 2) BNN priors/posteriors
# =========================
def prior_fn(dtype, shape, name, trainable, add_variable_fn):
    del name, trainable, add_variable_fn
    return tfd.Independent(
        tfd.Normal(
            loc=tf.zeros(shape, dtype=dtype),
            scale=tf.ones(shape, dtype=dtype)
        ),
        reinterpreted_batch_ndims=len(shape)
    )

posterior_fn = tfp.layers.default_mean_field_normal_fn(
    is_singular=False,
    loc_initializer=keras.initializers.Zeros(),
    untransformed_scale_initializer=keras.initializers.Constant(-2.2)  # ~ std 0.1 after softplus
)

def kl_sum(q, p, _):
    return 1e-5 * tf.reduce_sum(tfp.distributions.kl_divergence(q, p))

def build_bnn(input_dim: int):
    inputs = keras.Input(shape=(int(input_dim),), dtype="float32", name="x")
    x = tfp.layers.DenseReparameterization(
        64, activation="relu",
        kernel_prior_fn=prior_fn, kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum, bias_divergence_fn=kl_sum
    )(inputs)
    x = tfp.layers.DenseReparameterization(
        32, activation="relu",
        kernel_prior_fn=prior_fn, kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum, bias_divergence_fn=kl_sum
    )(x)
    outputs = tfp.layers.DenseReparameterization(
        1, activation=None,
        kernel_prior_fn=prior_fn, kernel_posterior_fn=posterior_fn,
        kernel_divergence_fn=kl_sum, bias_divergence_fn=kl_sum
    )(x)
    return keras.Model(inputs, outputs, name="BNN_gX")

# =========================
# 3) FIXED Cox partial likelihood loss
#    - full risk sets (prefix cumulative_logsumexp)
#    - Breslow tie handling
# =========================
@tf.function
def neg_log_partial_lik(y_true, y_pred):
    event = tf.cast(y_true[:, 0], tf.float32)
    time  = tf.cast(y_true[:, 1], tf.float32)
    risk  = tf.cast(tf.squeeze(y_pred, axis=-1), tf.float32)  # log-risk

    # sort by time descending
    order = tf.argsort(time, direction="DESCENDING")
    time  = tf.gather(time,  order)
    event = tf.gather(event, order)
    risk  = tf.gather(risk,  order)

    # prefix denominators: log(sum_{j<=i} exp(risk_j))
    lse_prefix = tf.math.cumulative_logsumexp(risk)

    # tie groups
    is_new = tf.concat([[True], tf.not_equal(time[1:], time[:-1])], axis=0)
    gid = tf.cumsum(tf.cast(is_new, tf.int32)) - 1

    is_end = tf.concat([tf.not_equal(time[:-1], time[1:]), [True]], axis=0)
    end_lse = tf.boolean_mask(lse_prefix, is_end)
    denom = tf.gather(end_lse, gid)

    loglik = tf.reduce_sum(event * (risk - denom))
    return -loglik / (tf.reduce_sum(event) + 1e-8)

# =========================
# 4) Train BNN correctly:
#    - FULL BATCH (Cox loss needs full risk sets)
#    - shuffle=False
# =========================
def train_bnn_and_get_g(X_tr, time_tr, event_tr, X_te, lr=1e-3, epochs=100):
    model = build_bnn(X_tr.shape[1])
    model.compile(optimizer=keras.optimizers.RMSprop(lr), loss=neg_log_partial_lik)

    y_tr = np.column_stack([event_tr, time_tr]).astype(np.float32)

    es = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
    timer = EpochTimer()

    model.fit(
        X_tr.astype(np.float32),
        y_tr,
        batch_size=X_tr.shape[0],   # FULL BATCH (critical)
        epochs=epochs,
        verbose=0,
        validation_split=0.2,       # ok if it still contains events; otherwise do manual split
        shuffle=False,
        callbacks=[es, timer]
    )

    g_tr = model.predict(X_tr.astype(np.float32), verbose=0).reshape(-1)
    g_te = model.predict(X_te.astype(np.float32), verbose=0).reshape(-1)
    return g_tr, g_te

# ============================================================
# 5) END-TO-END: from df_processed -> X,T,E -> split -> train
# ============================================================

# (A) Ensure your df_processed already has:
#     - num__DURATION (float days)  <-- must be computed and > 0
#     - num__Event (0/1)
#     - all encoded covariates including SECTION_FREQ
# and the date__* columns exist but will be dropped from X.

# --- filter out bad times (this fixes your Min T: nan) ---
dfv = df_processed.copy()
dfv = dfv[dfv["num__DURATION"].notna()].copy()
dfv = dfv[dfv["num__DURATION"] > 0].copy()   # survival time must be strictly positive
dfv = dfv[dfv["num__Event"].notna()].copy()

# --- build T,E ---
T = dfv["num__DURATION"].to_numpy(np.float32)
E = dfv["num__Event"].astype(int).to_numpy(np.int32)

# --- build X (keep SECTION_FREQ; drop leakage/date) ---
drop_cols = [
    "num__DURATION",
    "num__Event",
    "date__FRACTURE_TIMESTAMP",
    "date__LAYING_DATE",
    "date__USFDTIMESTAMP",
]
X_df = dfv.drop(columns=drop_cols, errors="ignore")
X = X_df.to_numpy(np.float32)

# --- sanity ---
print("NaNs in T:", np.isnan(T).sum())
print("Min T:", float(np.nanmin(T)))
assert np.isnan(T).sum() == 0
assert float(np.min(T)) > 0

# --- stratified split ---
X_train, X_test, y_time_tr, y_time_te, y_event_tr, y_event_te = train_test_split(
    X, T, E, test_size=0.2, random_state=42, stratify=E
)

print("Train events:", int(y_event_tr.sum()))
print("Test events:", int(y_event_te.sum()))

# --- scale features for BNN stability ---
scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train).astype(np.float32)
X_test_s  = scaler.transform(X_test).astype(np.float32)

# --- train BNN nonlinear term g(x) ---
g_tr, g_te = train_bnn_and_get_g(
    X_train_s, y_time_tr, y_event_tr, X_test_s, lr=1e-3, epochs=100
)

# ============================================================
# 6) HYBRID LINEAR COX on (AXLE_LOAD, GMTCARRIED, g_bnn)
# ============================================================

# Find indices of linear columns inside X_df columns
# (Your encoded names are like ord__AXLELOAD and num__GMTCARRIED)
colnames = list(X_df.columns)
def find_col(name_substr):
    hits = [i for i, c in enumerate(colnames) if name_substr in c]
    if len(hits) != 1:
        raise ValueError(f"Expected 1 match for {name_substr}, got {len(hits)}: {[colnames[i] for i in hits[:10]]}")
    return hits[0]

i_axle     = find_col("AXLELOAD")
i_gmt      = find_col("GMTCARRIED")
i_annual   = find_col("ANNUAL_GMT")
i_rail     = find_col("RAIL_SECTION")
i_service  = find_col("SERVICE_LIFE")
i_speed    = find_col("SPEED")

# OHE columns
i_track_lwr = find_col("TRACK_TYPE_LWR")
i_track_swr = find_col("TRACK_TYPE_SWR")
i_straight  = find_col("STRAIGHT_CURVE_STRAIGHT")

X_lin_tr = X_train[:, [i_axle,i_gmt,i_annual,i_rail,i_service,i_speed,i_track_lwr,i_track_swr,i_straight]]
X_lin_te = X_test[:,  [i_axle,i_gmt,i_annual,i_rail,i_service,i_speed,i_track_lwr,i_track_swr,i_straight]]

train_df = pd.DataFrame({
    "time": y_time_tr,
    "event": y_event_tr,
    "AXLE_LOAD": X_lin_tr[:,0],
    "GMT_CARRIED": X_lin_tr[:,1],
    "ANNUAL_GMT": X_lin_tr[:,2],
    "RAIL_SECTION": X_lin_tr[:,3],
    "SERVICE_LIFE": X_lin_tr[:,4],
    "SPEED": X_lin_tr[:,5],
    "TRACK_TYPE_LWR": X_lin_tr[:,6],
    "TRACK_TYPE_SWR": X_lin_tr[:,7],
    "STRAIGHT_CURVE_STRAIGHT": X_lin_tr[:,8],
    "g_bnn": g_tr
})

test_df = pd.DataFrame({
    "time": y_time_te,
    "event": y_event_te,
    "AXLE_LOAD": X_lin_te[:,0],
    "GMT_CARRIED": X_lin_te[:,1],
    "ANNUAL_GMT": X_lin_te[:,2],
    "RAIL_SECTION": X_lin_te[:,3],
    "SERVICE_LIFE": X_lin_te[:,4],
    "SPEED": X_lin_te[:,5],
    "TRACK_TYPE_LWR": X_lin_te[:,6],
    "TRACK_TYPE_SWR": X_lin_te[:,7],
    "STRAIGHT_CURVE_STRAIGHT": X_lin_te[:,8],
    "g_bnn": g_te
})

formula = """
AXLE_LOAD + GMT_CARRIED + ANNUAL_GMT + RAIL_SECTION +
SERVICE_LIFE + SPEED + TRACK_TYPE_LWR + TRACK_TYPE_SWR +
STRAIGHT_CURVE_STRAIGHT + g_bnn
"""



cph = CoxPHFitter()
cph.fit(train_df, duration_col="time", event_col="event",
        formula=formula)

print(cph.params_)

risk_tr = cph.predict_partial_hazard(train_df).values.ravel()
risk_te = cph.predict_partial_hazard(test_df).values.ravel()

c_tr = concordance_index(train_df["time"].values, -risk_tr, train_df["event"].values)
c_te = concordance_index(test_df["time"].values, -risk_te, test_df["event"].values)
print(f"C-index train={c_tr:.3f}  test={c_te:.3f}")

import numpy as np

# --- predicted survival curves for test set ---
# choose a grid within test follow-up, strictly inside max
t_min = float(np.min(y_time_te))
t_max = float(np.max(y_time_te))
eps = np.nextafter(t_max, -np.inf)  # strictly less than max
times = np.linspace(t_min, eps, 200)

surv_df = cph.predict_survival_function(test_df, times=times)  # shape: (len(times), n_test)

# --- predicted median survival time per sample ---
S = surv_df.to_numpy().T  # (n_test, n_times)

def median_time_from_curve(times, s_row):
    # first time S(t) <= 0.5; if never crosses, return max time
    idx = np.where(s_row <= 0.5)[0]
    return times[idx[0]] if len(idx) else times[-1]

t50_pred = np.array([median_time_from_curve(times, s_row) for s_row in S], dtype=float)

# --- RMSE on events only ---
mask_event = (y_event_te == 1)
rmse_t50 = np.sqrt(np.mean((t50_pred[mask_event] - y_time_te[mask_event]) ** 2))

print("RMSE (median survival time, events only):", rmse_t50)
print("Num events used:", int(mask_event.sum()))

!pip install scikit-survival

from sksurv.metrics import integrated_brier_score
from sksurv.util import Surv

# structured arrays
y_train_struct = Surv.from_arrays(y_event_tr.astype(bool), y_time_tr.astype(float))
y_test_struct  = Surv.from_arrays(y_event_te.astype(bool), y_time_te.astype(float))

# times must be within [min(test); max(test)) strictly
t_min = float(np.min(y_time_te))
t_max = float(np.max(y_time_te))
eps = np.nextafter(t_max, -np.inf)
times_ibs = np.linspace(t_min, eps, 200)

# survival predictions matrix: (n_test, n_times)
surv_df_ibs = cph.predict_survival_function(test_df, times=times_ibs)
S_pred = surv_df_ibs.to_numpy().T  # (n_test, n_times)

ibs = integrated_brier_score(
    y_train_struct,
    y_test_struct,
    S_pred,
    times_ibs
)

print("IBS:", float(ibs))

